### ISSUE TITLE
Improving performance by adding a sleep/delay function

### ISSUE THREAD

**Issue by naturalinteraction** [Lecrapouille/OffScreenCEF#5]
I believe adding usleep(10 * 1000) or SDL_Delay(10) improves responsiveness in the OpenGL and SDL examples.

**Comment by Lecrapouille** [comment]
@naturalinteraction where ? Why adding a delay will improve responsiveness but not the opposite ? Did you mean https://stackoverflow.com/questions/50361975/sdl-framerate-cap-implementation instead ?

**Comment by naturalinteraction** [comment]
Good question! I added it in the OpenGL sample in CEFGLWindow::update(), right after CefDoMessageLoopWork(), and in the SDL sample right after SDL_RenderPresent(m_renderer).

It turns out I was wrong: you already have enabled VSYNC in both samples (with glfwSwapInterval(1) and SDL_RENDERER_PRESENTVSYNC, respectively). So the extra delay doesn't do much of a difference, possibly reducing the frame rate a little.

My idea was that with a main loop trying to work as fast as possible (without VSYNC), that thread could consume extra cycles, slowing  down the other asynchronous process. 

Closing. Thank you for your work.

**Comment by Lecrapouille** [comment]
@naturalinteraction what you can do (I did not try) to make it more reactive:

- is to use the threaded version of CefDoMessageLoopWork (I do not remember its name) which will self schedule communication between CEF process instead of the polling version (used in my examples) manually called by the rendering loop (in my example). https://magpcss.org/ceforum/viewtopic.php?f=6&t=12913

- the paint callback: do not render the whole image sent by CEF (const void *buffer, int width, int height) but just refresh dirty rectangles (const RectList &dirtyRects).

https://github.com/Lecrapouille/OffScreenCEF/blob/bf0cb29cda0549be2109643fa19caf14c1941048/cefsimple_opengl/BrowserView.cpp#L148-L150

Do not hesitate to create a pull request if you have made working examples of these two points :)
